version: "3.7"
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: db_app
    command: -p 5435
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5435
    env_file:
      - .env-non-dev

  server_app:
    build:
      context: ./server dir/
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

  nginx:
      depends_on:
          - server_app
      container_name: proxy_app
      build:
          context: ./client dir/
          dockerfile: Dockerfile
      ports:
          - 3000:80

volumes:
  pgdata:
