"""The relationship between workout difficulties and workouts has been removed

Revision ID: 8601d06e7e88
Revises: ac40e42c3099
Create Date: 2023-11-03 19:43:59.490622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8601d06e7e88'
down_revision: Union[str, None] = 'ac40e42c3099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_table', sa.Column('difficulty', sa.String(), nullable=False))
    op.drop_constraint('workout_table_difficulty_id_fkey', 'workout_table', type_='foreignkey')
    op.drop_column('workout_table', 'difficulty_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_table', sa.Column('difficulty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('workout_table_difficulty_id_fkey', 'workout_table', 'difficulty_workout_table', ['difficulty_id'], ['id'])
    op.drop_column('workout_table', 'difficulty')
    # ### end Alembic commands ###
